# Must load Pyhthon module, defult=C++
load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "data_models_lib",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
)