TestBeds:
  - Name: Google_Mobly_TestBed
    Controllers:
      AndroidDevice:
        - serial: "emulator-5554"

    TestParams:
      wifi_ssid: "sheltercafe"
      wifi_pwd: "shelter5118"
      target_app_pkg: "com.darkempire78.opencalculator"
      test_app_path: "tests/test_data/apks/com.darkempire78.opencalculator_53.apk"
      test_app_screenshot_path: "screenshot"