TestBeds:
  - Name: Google_Mobly_TestBed
    Controllers:
      AndroidDevice:
        - serial: "28011FQHN00214"

    TestParams:
      wifi_ssid: "sheltercafe"
      wifi_pwd: "shelter5118"
      target_app_pkg: "com.darkempire78.opencalculator"
      test_app_path: "/Users/aaron/Desktop/Learning Roadmap & Progress/STAGE 5: ENTERPRISE MOBLY ARCHITECHTURE/tests/test_data/apks/com.darkempire78.opencalculator_53.apk"
      test_app_screenshot_path: "/Users/aaron/Desktop/Learning Roadmap & Progress/STAGE 5: ENTERPRISE MOBLY ARCHITECHTURE/screenshot"