TestBeds:
  - Name: Google_Mobly_TestBed
    Controllers:
      AndroidDevice:
        - serial: "28011FQHN00214"

    TestParams:
      wifi_ssid: "sheltercafe"
      wifi_pwd: "shelter5118"
      target_app_pkg_for_calculator: "com.darkempire78.opencalculator"
      target_app_pkg_for_chrome: "com.android.chrome"
      target_app_for_settings: "com.android.settings"
      test_app_path_for_calculator: "automation_mobly/tests/test_data/apks/com.darkempire78.opencalculator.apk"
      test_app_screenshot_path: "automation_mobly/screenshot"